version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies for unit test...

  build:
    commands:
      - echo Running backend unit tests...
      - cd backend
      - chmod +x ./gradlew
      - ./gradlew test --no-daemon
      - cd ..

reports:
  unit-tests:
    files:
      - '**/*.xml'
    base-directory: 'backend/build/test-results/test'
    file-format: 'JUNITXML'