apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce   # EBS는 RWO만 지원 (한 번에 한 Pod만 쓰기 마운트 가능) -> Backend replica 1개 전제와 일치
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi