apiVersion: apps/v1
kind: Deployment
metadata:
  name: aivle-mini6-backend
  labels:
    app: aivle-mini6-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: aivle-mini6-backend
  template:
    metadata:
      labels:
        app: aivle-mini6-backend
    spec:
      containers:
        - name: backend
          image: 416225317325.dkr.ecr.us-east-1.amazonaws.com/aivle-mini6-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AWS_S3_BUCKET
              value: "aivle-mini6-book-covers-01-01"
            - name: AWS_REGION
              value: "us-east-1"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:file:/app/data/bookdb"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 6
          volumeMounts:
            - name: h2-data
              mountPath: /app/data
      volumes:
        - name: h2-data
          persistentVolumeClaim:
            claimName: h2-ebs-pvc